import React from 'react'

const ReturnPolicy = () => {
  return (
    <>
     <div className="refund-policy m-10">
      <h1 className="text-2xl font-bold my-4">Refund Policy for PowerPlus</h1>
      <p className="font-semibold my-2">Effective Date: 13 June, 2024</p>
      
      <h2 className="text-xl font-bold my-4">1. Introduction</h2>
      <p>
        PowerPlus ("we," "us," "our") is a Power Token vending platform connected to all Distribution Companies (DISCOs) in Nigeria. We act as a reseller for electricity tokens generated by DISCOs. This Refund Policy outlines the procedures and conditions under which customers may request refunds or assistance in the event of issues with token generation or payment failures.
      </p>
      
      <h2 className="text-xl font-bold my-4">2. Token Generation Issues</h2>
      <p>In cases where electricity tokens are not generated successfully:</p>
      <ol className="list-decimal ml-6">
        <li><strong>Immediate Assistance:</strong> Customers should first contact PowerPlus customer support for immediate assistance. We will verify the transaction details and attempt to resolve the issue promptly.</li>
        <li><strong>Referral to DISCOs:</strong> If the issue is due to token generation by the DISCOs, PowerPlus will refer the matter to the relevant DISCO. This process may take up to 7 days for resolution. We will keep you informed of the progress and any updates provided by the DISCO.</li>
        <li><strong>Resolution:</strong> Upon confirmation from the DISCO that the issue is resolved, we will ensure that the electricity tokens are delivered to you. If the DISCO is unable to generate the tokens, we will provide a full refund of the transaction amount.</li>
      </ol>

      <h2 className="text-xl font-bold my-4">3. Payment Failures</h2>
      <p>In cases where payment fails or is not processed correctly:</p>
      <ol className="list-decimal ml-6">
        <li><strong>Verification:</strong> Customers should contact PowerPlus customer support to report the payment failure. We will verify the transaction and payment status.</li>
        <li><strong>Referral to Bank:</strong> If the payment issue is confirmed to be on the side of the payment processor or the customer's bank, we will advise the customer to contact their bank directly for a refund or resolution. PowerPlus does not have control over bank-related payment failures and thus cannot process refunds in such cases.</li>
      </ol>

      <h2 className="text-xl font-bold my-4">4. Refund Process</h2>
      <p>
        <strong>Refund Eligibility:</strong> Refunds are eligible for transactions where token generation failed due to DISCOs' errors and cannot be resolved within the specified timeframe.
      </p>
      <p>
        <strong>Refund Method:</strong> Refunds will be processed using the same payment method used for the original transaction. The time it takes for the refund to be credited to your account may vary depending on your payment provider.
      </p>
      <p>
        <strong>Refund Timeline:</strong> Once a refund is approved, it will be processed within 7 business days. However, the actual time for the refund to reflect in your account may depend on your bank or payment provider's policies.
      </p>

      <h2 className="text-xl font-bold my-4">5. Contact Information</h2>
      <p>For any issues related to token generation, payment failures, or refund requests, please contact PowerPlus customer support:</p>
      <ul className="list-disc ml-6">
        <li>Email: <a href="mailto:info@powerplus.ng" className="text-blue-600">info@powerplus.ng</a></li>
        <li>Phone: 0707 330 5599</li>
        <li>Address: 15 Olusegun Obasanjo Street, Peace Court Estate, Lokogoma, Abuja</li>
      </ul>

      <h2 className="text-xl font-bold my-4">6. Amendments to This Refund Policy</h2>
      <p>PowerPlus reserves the right to amend this Refund Policy at any time. Any changes will be posted on this page with an updated effective date. Customers are encouraged to review this policy periodically for any updates.</p>

      <h2 className="text-xl font-bold my-4">7. Conclusion</h2>
      <p>PowerPlus is dedicated to providing reliable service and support for our customers. We appreciate your understanding and patience in resolving any issues related to electricity token vending.</p>

      <p className="font-bold">PowerPlus</p>
      <p className="font-bold">Metronet Business Resources Ltd</p>
    </div>
    </>
  )
}

export default ReturnPolicy